### PR TITLE
Show distance and timer over pokemon annotations

### PR DESCRIPTION
**Pull request by evshade**
Add Time and Timer labels
Add Distance label
Add settings to switch them

### CODE REVIEW

**Comment by evshade** [comment]
Also, @istornz what do you think about creating some kind of constants file and/or settings helper? There are a lot of string constants for settings and notifications and its easy to misspell.

**Comment by evshade** [comment]
For now distance is calculated from users position, not manually set point. Im not sure how to handle this case and when to switch between them.

**Comment by istornz** [comment]
Thx for your feature !
But there are some conflicts... Can you patch that (I don't have time now)

**Comment by istornz** [comment]
And yeah good idea for constants. It would be very appreciated :)

**Comment by evshade** [comment]
Can you please point me to conflicts? Im not familiar with merging PRs from other repo w/o write access.

**Comment by istornz** [comment]
Yes : 
- Merge conflict in iPokeGo/MapViewController.m
- Merge conflict in iPokeGo/Base.lproj/Main.storyboard

**Comment by istornz** [comment]
I think you started to work on the older version of the project (without radar).
I made a lot of change especially in the mapviewcontroller.m

**Comment by evshade** [comment]
Yep. Should I pull master to Distance_and_Timer_Features and then fix conflicts?

**Comment by istornz** [comment]
If you want :)

**Comment by evshade** [comment]
@istornz any conflicts now?

**Comment by istornz** [comment]
No thx :)

**Comment by istornz** [comment]
Great update good work !

**Comment by aloysiusan** [comment]
@evshade there's a bug with the timer, after the app Goes in background and becomes active again, the timer doesn't update to the real time left. For example: if there's a Pokémon with 10 min left, and I press the home button and 5 min later I open the app again...the timer will be at 10 min left instead of 5... these are screeshots from the web version and the iOS version 

img_1210
img_1211

**Pull request merged**
