### PR TITLE
Added: High resolution Pokemon icons

### PR DESCRIPTION
**Pull request by aloysiusan**
Replaced old sprites with high resolution icons, used on new version of web client

### CODE REVIEW

**Comment by jankcat** [comment]
:white_check_mark: you have my vote (not that it counts for anything!)

**Comment by blg-andreasbraun** [comment]
@aloysiusan 
I noticed that you cut the icons from a sprite sheet on every call to tableView(_:cellForRowAtIndexPath:) which is sometimes really slow and leads to a noticeable lag when opening the View Controller.

Was there any reason to not just use UIImage(named:) and load the image by the Pokémon number?

**Comment by aloysiusan** [comment]
@blg-andreasbraun Maybe not the best method, however I couldn't find each image individually, just the sprite sheet...I took the sprite sheet from the original web client https://github.com/AHAAAAAAA/PokemonGo-Map/blob/master/static/icons-large-sprite.png
I can crop them manually (or someone else if want) and add each icon to the project

**Comment by blg-andreasbraun** [comment]
@aloysiusan I have an app, that does exactly that, could cut them and upload them later :)

**Pull request merged**
