### PR TITLE
Add "real" high-resolution images for Pokemon #1-#151

### PR DESCRIPTION
**Pull request by likers**
I replaced all 151 pokemons' image with 260x240p image, which comes from http://pokemongo.gamepress.gg, they are much more beautiful and elegant. I personally, literally don't like the current "crop from large image" approach. 

What's more, the new common and favorite list doesn't work, I will debug and pull another fix later tomorrow.

### CODE REVIEW

**Comment by istornz** [comment]
Hello thx for your commit but there are some conflicts :/

**Comment by likers** [comment]
hello，

OK I will double check and retry :)

**Comment by markvl91** [comment]
You're breaking the configurability of common pokemon with commit 254b071, can you please avoid that?

Furthermore, I think the icons are a bit of a subjective thing. I like the current icons and that they match the actual Pokemon Go and PokemonGo Map icons, so I'd consider this a downgrade. Just my two cents.

**Comment by likers** [comment]
Hi markvl91,

Thank you for the comment, Yes I hard coded common pokemon list for my self-use. I will revert it soon.

**Comment by likers** [comment]
Hi all, I've revert and committed, please check if there's still conflicts.

Regarding to markvl91's opinion on the icons, I still believe a good-looking UI with high quality images is necessary for users. I've attached two screenshots comparing the difference. Also my friends are 100% voted to newer images.
img_4293
img_4294

**Comment by markvl91** [comment]
I'll agree the current images are fuzzier than I'd like, but I respectfully disagree on the new images with regards their style. I find that It doesn't fit with Pokemon Go's 3D style.

**Comment by fraannk** [comment]
These suggested zubats for example doesn't look like the one in the game, and that might confuse "noobs", so I suggest that we keep using the ones from the game. I recommend disabling the x1,5 scaling in the code, because they get too big and fuzzy. At original 1x size they look great on a retina device.

**Comment by istornz** [comment]
I also prefer the old icons for the same reasons as @fraannk 
But thx for you suggestion !

**Comment by likers** [comment]
Alright, but I believe "noobs" will not even come to this repo XD. What's more please have enough confident for users, I spread this app to my friends, some "noobs" of them never seen pokemons before, but they all recognized all pokemons at once. 
I'll keep looking for perfect icons.

**Pull request closed without merging**
