### PR TITLE
Follow user location.

### PR DESCRIPTION
**Pull request by dmunozfer**
I added option to follow user location #186 

If the user click GPS button, follow location is activated.
If the user makes a long press on the map, follow location is disabled.

When follow location is active, a new location is sent to the server when:
- Distance from last location update is greater than 500m.
- Time from last location update send to server is greater than 120 seconds.

### CODE REVIEW

**Comment by markvl91** [comment]
So wait, hitting the "go to my location" button now instead activates follow location behavior? I would've liked to have seen it as an addition, not replacing something I use pretty often without wanting to have it follow my location. 
Maybe this can be done in another way that doesn't remove functionality?

Also, perhaps make it so that it stops following when a user pans the mapview, this usually indicates the user is no longer interested in local updates.

This implementation also doesn't show any indicator of activity, perhaps (also taking account my first point) you could have it activate on a long press on the GPS button, with that pulsating for as long as following is active. Combine that with stopping follow on mapview pan, and I think it would be a much better way to implement this feature.

**Comment by istornz** [comment]
I'm agree with @markvl91 would be more interresting to add a new option/button to activate this than remplacing a functionnality.

**Comment by dmunozfer** [comment]
I changed the code by following your suggestions. Let me know what you think of this changes.

**Comment by dmunozfer** [comment]
**Follow location summarize:**
- Disabled by default
- Enabled with long press in "go to my location" (this disable scan location)
- Disable follow location when a user pans the mapview
- Map location tracker dimmed mode by default, normal mode when follow location is enabled

When follow location is active, a new location is sent to the server when:

- Distance from last location update is greater than 500m.
- Time from last location update send to server is greater than 120 seconds.

**Pull request merged**
